services:
  web:
    image: nginx:latest # Using the default Nginx image with custom configuration.
    volumes:
      # Mount the application code for live updates
      - ./:/var/www/public:ro
      # Mount the Nginx configuration file
      - ./docker/development/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      # Map port 80 inside the container to the port specified by 'NGINX_PORT' on the host machine
      - "80:80"
    networks:
      - laravel-development
    depends_on:
      php-fpm:
        condition: service_started # Wait for php-fpm to start

  php-fpm:
    # For the php-fpm service, we will use our common PHP-FPM Dockerfile with the development target
    build:
      context: .
      dockerfile: ./docker/production/php-fpm/Dockerfile
      target: production
    user: www-data
    volumes:
      # Mount the application code for live updates
      - ./:/var/www:ro
    networks:
      - laravel-production
    depends_on:
      mysql:
        condition: service_started # Wait for postgres to start

  mysql:
    image: mysql:8.0
    environment:
        - MYSQL_DATABASE=app
        - MYSQL_USER=laravel
        - MYSQL_PASSWORD=secret
        - MYSQL_ROOT_PASSWORD=root
    volumes:
        - mysql-data-production:/var/lib/mysql
    networks:
        - laravel-production

  # postgres:
  #   image: postgres:18
  #   ports:
  #     - "${POSTGRES_PORT:-5432}:5432"
  #   environment:
  #     - POSTGRES_DB=app
  #     - POSTGRES_USER=laravel
  #     - POSTGRES_PASSWORD=secret
  #   volumes:
  #     - postgres-data-development:/var/lib/postgresql
  #   networks:
  #     - laravel-production

  redis:
    image: redis:alpine
    networks:
      - laravel-production

networks:
  laravel-production:

volumes:
  mysql-data-production:
# volumes:
#   postgres-data-production:
